import { Boss, BossId } from "./boss.type";

export const BOSS_CONFIG: Record<BossId, Boss> = {
  bogar: {
    id: "bogar",
    name: "Bogar",
    drops: [
      "rubyCollar",
      "sorrowScarf",
      "feltFedora",
      "titaniumTiara",
      "chunkyKnitScarf",
      "fallCamelScarf",
      "topHat",
      "cowboyHat",
      "nailBuffers",
      "leatherJournal",
      "diamondCollar",
      "seaDolphinFloat",
      "shitakeMushroom",
      "baseBallCap",
      "retroPinkFlowerCollar",
      "redBowTie",
      "peachDolphinFloat",
      "turquoiseHeartCollar",
      "daisyChain",
      "leaf",
      "cosmosFlower",
      "pinkDandelion",
      "dandelion",
      "amanitaMushroom",
    ],
  },
  deathQuack: {
    id: "deathQuack",
    name: "Death Quack",
    drops: [
      "bejeweledPinkScarf",
      "mermaidScarf",
      "unicornHorns",
      "rainbowPartyHat",
      "blackSpikedCollar",
      "pinkSpikedCollar",
      "purpleBeanie",
      "redHat",
      "espressoShot",
      "fluffyPillow",
      "blueRibbonScarf",
      "maroonRibbonScarf",
      "backwardsCap",
      "beigeBeret",
      "retroPinkFlowerCollar",
      "redBowTie",
      "peachDolphinFloat",
      "turquoiseHeartCollar",
      "daisyChain",
      "leaf",
      "cosmosFlower",
      "pinkDandelion",
      "dandelion",
      "amanitaMushroom",
    ],
  },
  krakoth: {
    id: "krakoth",
    name: "Krakoth",
    drops: [
      "wizardCape",
      "blueTie",
      "pirateHat",
      "karenHair",
      "goldDiamondNecklace",
      "pinkSpikedCollar",
      "purpleBeanie",
      "redHat",
      "weightedBlanket",
      "espressoShot",
      "greenRibbonScarf",
      "platinumDiamondNecklace",
      "shitakeMushroom",
      "deathCapMushroom",
      "retroPinkFlowerCollar",
      "redBowTie",
      "peachDolphinFloat",
      "turquoiseHeartCollar",
      "daisyChain",
      "leaf",
      "cosmosFlower",
      "pinkDandelion",
      "dandelion",
      "amanitaMushroom",
    ],
  },
  shift: {
    id: "shift",
    name: "Shift",
    drops: [
      "watermelonSpikedCollar",
      "serpentScarf",
      "pinwheelHat",
      "pearlClocheHat",
      "fallCamelScarf",
      "aquaSpikedCollar",
      "yellowPalmCap",
      "hibiscusFlower",
      "leatherJournal",
      "softDumbbell",
      "redRibbonScarf",
      "blueButterflyChain",
      "deathCapMushroom",
      "tropicalWreath",
      "retroPinkFlowerCollar",
      "redBowTie",
      "peachDolphinFloat",
      "turquoiseHeartCollar",
      "daisyChain",
      "leaf",
      "cosmosFlower",
      "pinkDandelion",
      "dandelion",
      "amanitaMushroom",
    ],
  },
  flint: {
    id: "flint",
    name: "Flint",
    drops: [
      "rubyCollar",
      "sorrowScarf",
      "feltFedora",
      "titaniumTiara",
      "chunkyKnitScarf",
      "fallCamelScarf",
      "topHat",
      "cowboyHat",
      "nailBuffers",
      "leatherJournal",
      "diamondCollar",
      "seaDolphinFloat",
      "shitakeMushroom",
      "baseBallCap",
      "retroPinkFlowerCollar",
      "redBowTie",
      "peachDolphinFloat",
      "turquoiseHeartCollar",
      "daisyChain",
      "leaf",
      "cosmosFlower",
      "pinkDandelion",
      "dandelion",
      "amanitaMushroom",
    ],
  },
  vulko: {
    id: "vulko",
    name: "Vulko",
    drops: [
      "enviousScarf",
      "cakeScarf",
      "floralCrochetHat",
      "wizardHat",
      "cowboyScarf",
      "hibiscusChain",
      "bluePalmCap",
      "hibiscusFlower",
      "stressBall",
      "softDumbbell",
      "greenRibbonScarf",
      "platinumDiamondNecklace",
      "batHeadband",
      "tropicalWreath",
      "retroPinkFlowerCollar",
      "redBowTie",
      "peachDolphinFloat",
      "turquoiseHeartCollar",
      "daisyChain",
      "leaf",
      "cosmosFlower",
      "pinkDandelion",
      "dandelion",
      "amanitaMushroom",
    ],
  },
  voidweaver: {
    id: "voidweaver",
    name: "Voidweaver",
    drops: [
      "lemonDolphinFloat",
      "spiderNecklace",
      "bejeweledCowboyHat",
      "iceCreamHat",
      "chunkyKnitScarf",
      "warmPinkScarf",
      "topHat",
      "spiderHat",
      "lycheeCandle",
      "stressBall",
      "greenRibbonScarf",
      "seaDolphinFloat",
      "shitakeMushroom",
      "rubyHairBow",
      "retroPinkFlowerCollar",
      "redBowTie",
      "peachDolphinFloat",
      "turquoiseHeartCollar",
      "daisyChain",
      "leaf",
      "cosmosFlower",
      "pinkDandelion",
      "dandelion",
      "amanitaMushroom",
    ],
  },
  harold: {
    id: "harold",
    name: "Harold",
    drops: [
      "bubblegumScarf",
      "jellyfishScarf",
      "icyTiara",
      "chefHat",
      "cowboyScarf",
      "hibiscusChain",
      "cowboyHat",
      "bluePalmCap",
      "nailBuffers",
      "fluffyPillow",
      "diamondCollar",
      "lavenderRibbonScarf",
      "batHeadband",
      "baseBallCap",
      "retroPinkFlowerCollar",
      "redBowTie",
      "peachDolphinFloat",
      "turquoiseHeartCollar",
      "daisyChain",
      "leaf",
      "cosmosFlower",
      "pinkDandelion",
      "dandelion",
      "amanitaMushroom",
    ],
  },
  quasar: {
    id: "quasar",
    name: "Quasar",
    drops: [
      "princesCollar",
      "rubberRingDonut",
      "specialTopHat",
      "plungerHat",
      "orangeButterflyChain",
      "blackSpikedCollar",
      "coralSunHat",
      "peonyWreath",
      "yogaMat",
      "fuzzyMittens",
      "blueRibbonScarf",
      "yellowRibbonScarf",
      "beeAntennae",
      "cherryBlossomCrown",
      "retroPinkFlowerCollar",
      "redBowTie",
      "peachDolphinFloat",
      "turquoiseHeartCollar",
      "daisyChain",
      "leaf",
      "cosmosFlower",
      "pinkDandelion",
      "dandelion",
      "amanitaMushroom",
    ],
  },
  breakfastClub: {
    id: "breakfastClub",
    name: "Breakfast Club",
    drops: [
      "paisleyCowboyScarf",
      "checkeredScarf",
      "goldenHalo",
      "redHorns",
      "orangeButterflyChain",
      "goldDiamondNecklace",
      "peonyWreath",
      "spiderHat",
      "weightedBlanket",
      "fuzzyMittens",
      "yellowRibbonScarf",
      "lavenderRibbonScarf",
      "rubyHairBow",
      "cherryBlossomCrown",
      "retroPinkFlowerCollar",
      "redBowTie",
      "peachDolphinFloat",
      "turquoiseHeartCollar",
      "daisyChain",
      "leaf",
      "cosmosFlower",
      "pinkDandelion",
      "dandelion",
      "amanitaMushroom",
    ],
  },
  galax: {
    id: "galax",
    name: "Galax",
    drops: [
      "anxietyScarf",
      "angryScarf",
      "silkTopHat",
      "cakeHat",
      "warmPinkScarf",
      "aquaSpikedCollar",
      "coralSunHat",
      "yellowPalmCap",
      "lycheeCandle",
      "yogaMat",
      "redRibbonScarf",
      "blueButterflyChain",
      "beeAntennae",
      "deathCapMushroom",
      "retroPinkFlowerCollar",
      "redBowTie",
      "peachDolphinFloat",
      "turquoiseHeartCollar",
      "daisyChain",
      "leaf",
      "cosmosFlower",
      "pinkDandelion",
      "dandelion",
      "amanitaMushroom",
    ],
  },
};

export const getBoss = (id: BossId) => BOSS_CONFIG[id];
