import { Vivid, VividName } from "./vivid.type";

export const VOID_VIVIDS_CONFIG: Record<VividName, Vivid> = {
  Phantom: {
    name: "Phantom",
    rarity: "Rare",
    colors: {
      primary: "#FFFFFF",
      secondary: "#E9E9F4",
      tertiary: "#000000",
    },
    cost: 10,
    description: "+5% speed",
    type: "Void",
  },
  Ephemeral: {
    name: "Ephemeral",
    rarity: "Rare",
    colors: {
      primary: "#6C95F8",
      secondary: "#7CBDF9",
      tertiary: "#D9E3F9",
    },
    cost: 15,
    description: "+5% stamina",
    type: "Void",
  },
  Celestial: {
    name: "Celestial",
    rarity: "Rare",
    colors: {
      primary: "#F5C045",
      secondary: "#F8D849",
      tertiary: "#5DCACB",
    },
    cost: 20,
    description: "+5% defense",
    type: "Void",
  },
  Cataclysmic: {
    name: "Cataclysmic",
    rarity: "Rare",
    colors: {
      primary: "#BD4567",
      secondary: "#EA3526",
      tertiary: "#2F4BCB",
    },
    cost: 25,
    description: "+5% attack",
    type: "Void",
  },

  Jaded: {
    name: "Jaded",
    rarity: "Fabled",
    colors: {
      primary: "#CCFDFE",
      secondary: "#D9D9FC",
      tertiary: "#6CE5E6",
    },
    cost: 50,
    description: "+5% healing effectiveness",
    type: "Void",
  },
  Ethereal: {
    name: "Ethereal",
    rarity: "Fabled",
    colors: {
      primary: "#B6AEF4",
      secondary: "#EAD0D0",
      tertiary: "#BDFDFE",
    },
    cost: 75,
    description: "+2% critical chance",
    type: "Void",
  },
  Illusive: {
    name: "Illusive",
    rarity: "Fabled",
    colors: {
      primary: "#7391D6",
      secondary: "#919FF8",
      tertiary: "#D7B1F0",
    },
    cost: 100,
    description: "+2.5% boss damage",
    type: "Void",
  },
  Cryptic: {
    name: "Cryptic",
    rarity: "Fabled",
    colors: {
      primary: "#39778C",
      secondary: "#5F9ABB",
      tertiary: "#89E1FC",
    },
    cost: 125,
    description: "+2.5% basic attack damage",
    type: "Void",
  },

  Arcane: {
    name: "Arcane",
    rarity: "Mythical",
    colors: {
      primary: "#5B5BAD",
      secondary: "#63639D",
      tertiary: "#FFFFFF",
    },
    cost: 270,
    description: "+10% healing effectiveness",
    type: "Void",
  },
  Resolute: {
    name: "Resolute",
    rarity: "Mythical",
    colors: {
      primary: "#53617F",
      secondary: "#7283AC",
      tertiary: "#C6F1FD",
    },
    cost: 405,
    description: "+5% boss damage",
    type: "Void",
  },
  Fathomless: {
    name: "Fathomless",
    rarity: "Mythical",
    colors: {
      primary: "#000000",
      secondary: "#12144A",
      tertiary: "#445064",
    },
    cost: 540,
    description: "+10% critical damage",
    type: "Void",
  },
  Elemental: {
    name: "Elemental",
    rarity: "Mythical",
    colors: {
      primary: "#1A0D06",
      secondary: "#37260A",
      tertiary: "#FAE38A",
    },
    cost: 675,
    description: "+2% armor penetration",
    type: "Void",
  },

  Corrosive: {
    name: "Corrosive",
    rarity: "Absurd",
    colors: {
      primary: "#081807",
      secondary: "#97FC8C",
      tertiary: "#EC5AB3",
    },
    cost: 1470,
    description: "+20% first attack damage",
    type: "Void",
  },
  Unidentified: {
    name: "Unidentified",
    rarity: "Absurd",
    colors: {
      primary: "#82C0EC",
      secondary: "#92DEC9",
      tertiary: "#EA3323",
    },
    cost: 2205,
    description: "Reduce damage taken by 20% on the first hit",
    type: "Void",
  },
  Intoxicating: {
    name: "Intoxicating",
    rarity: "Absurd",
    colors: {
      primary: "#2E04F5",
      secondary: "#5737F5",
      tertiary: "#EA33DE",
    },
    cost: 2940,
    description: "Deal 3% of enemy's max health as bonus damage on each hit.",
    type: "Void",
  },
  Tartarean: {
    name: "Tartarean",
    rarity: "Absurd",
    colors: {
      primary: "#02000B",
      secondary: "#000083",
      tertiary: "#EA3323",
    },
    cost: 3675,
    description: "Gain 1% attack each turn",
    type: "Void",
  },
};

export const DEFAULT_VIVIDS_CONFIG = {
  Phantom: {
    name: "Phantom",
    rarity: "Rare",
    colors: {
      primary: "",
      secondary: "",
      tertiary: "",
    },
    cost: 10,
    description: "",
    type: "Earth",
  },
  Ephemeral: {
    name: "Ephemeral",
    rarity: "Rare",
    colors: {
      primary: "",
      secondary: "",
      tertiary: "",
    },
    cost: 15,
    description: "",
    type: "Earth",
  },
  Celestial: {
    name: "Celestial",
    rarity: "Rare",
    colors: {
      primary: "",
      secondary: "",
      tertiary: "",
    },
    cost: 20,
    description: "",
    type: "Earth",
  },
  Cataclysmic: {
    name: "Cataclysmic",
    rarity: "Rare",
    colors: {
      primary: "",
      secondary: "",
      tertiary: "",
    },
    cost: 25,
    description: "",
    type: "Earth",
  },

  Jaded: {
    name: "Jaded",
    rarity: "Fabled",
    colors: {
      primary: "",
      secondary: "",
      tertiary: "",
    },
    cost: 50,
    description: "",
    type: "Earth",
  },
  Ethereal: {
    name: "Ethereal",
    rarity: "Fabled",
    colors: {
      primary: "",
      secondary: "",
      tertiary: "",
    },
    cost: 75,
    description: "",
    type: "Earth",
  },
  Illusive: {
    name: "Illusive",
    rarity: "Fabled",
    colors: {
      primary: "",
      secondary: "",
      tertiary: "",
    },
    cost: 100,
    description: "",
    type: "Earth",
  },
  Cryptic: {
    name: "Cryptic",
    rarity: "Fabled",
    colors: {
      primary: "",
      secondary: "",
      tertiary: "",
    },
    cost: 125,
    description: "",
    type: "Earth",
  },

  Arcane: {
    name: "Arcane",
    rarity: "Mythical",
    colors: {
      primary: "",
      secondary: "",
      tertiary: "",
    },
    cost: 270,
    description: "",
    type: "Earth",
  },
  Resolute: {
    name: "Resolute",
    rarity: "Mythical",
    colors: {
      primary: "",
      secondary: "",
      tertiary: "",
    },
    cost: 405,
    description: "",
    type: "Earth",
  },
  Fathomless: {
    name: "Fathomless",
    rarity: "Mythical",
    colors: {
      primary: "",
      secondary: "",
      tertiary: "",
    },
    cost: 540,
    description: "",
    type: "Earth",
  },
  Elemental: {
    name: "Elemental",
    rarity: "Mythical",
    colors: {
      primary: "",
      secondary: "",
      tertiary: "",
    },
    cost: 675,
    description: "",
    type: "Earth",
  },

  Corrosive: {
    name: "Corrosive",
    rarity: "Absurd",
    colors: {
      primary: "",
      secondary: "",
      tertiary: "",
    },
    cost: 1470,
    description: "",
    type: "Earth",
  },
  Unidentified: {
    name: "Unidentified",
    rarity: "Absurd",
    colors: {
      primary: "",
      secondary: "",
      tertiary: "",
    },
    cost: 2205,
    description: "",
    type: "Earth",
  },
  Intoxicating: {
    name: "Intoxicating",
    rarity: "Absurd",
    colors: {
      primary: "",
      secondary: "",
      tertiary: "",
    },
    cost: 2940,
    description: "",
    type: "Earth",
  },
  Tartarean: {
    name: "Tartarean",
    rarity: "Absurd",
    colors: {
      primary: "",
      secondary: "",
      tertiary: "",
    },
    cost: 3675,
    description: "",
    type: "Earth",
  },
};
