/* eslint-disable @typescript-eslint/no-require-imports */

import { ImageSourcePropType } from "react-native";

import { ItemId } from "./item.type";

const ITEMS_IMAGES: Record<ItemId, ImageSourcePropType> = {
  // COMMON
  retroPinkFlowerCollar: require("../../assets/images/items/assets_imgs_items_retropinkflowercollar.png"),
  redBowTie: require("../../assets/images/items/assets_imgs_items_redbowtie.png"),
  peachDolphinFloat: require("../../assets/images/items/assets_imgs_items_peachdolphinfloat.png"),
  turquoiseHeartCollar: require("../../assets/images/items/assets_imgs_items_turquoiseheartcollar.png"),
  daisyChain: require("../../assets/images/items/assets_imgs_items_daisychain.png"),
  leaf: require("../../assets/images/items/assets_imgs_items_leaf.png"),
  cosmosFlower: require("../../assets/images/items/assets_imgs_items_cosmosflower.png"),
  pinkDandelion: require("../../assets/images/items/assets_imgs_items_pinkdandelion.png"),
  dandelion: require("../../assets/images/items/assets_imgs_items_dandelion.png"),
  amanitaMushroom: require("../../assets/images/items/assets_imgs_items_amanitamushroom.png"),

  // RARE
  diamondCollar: require("../../assets/images/items/assets_imgs_items_diamondcollar.png"),
  redRibbonScarf: require("../../assets/images/items/assets_imgs_items_redribbonscarf.png"),
  blueRibbonScarf: require("../../assets/images/items/assets_imgs_items_blueribbonscarf.png"),
  yellowRibbonScarf: require("../../assets/images/items/assets_imgs_items_yellowribbonscarf.png"),
  greenRibbonScarf: require("../../assets/images/items/assets_imgs_items_greenribbonscarf.png"),
  lavenderRibbonScarf: require("../../assets/images/items/assets_imgs_items_lavenderribbonscarf.png"),
  seaDolphinFloat: require("../../assets/images/items/assets_imgs_items_seadolphinfloat.png"),
  blueButterflyChain: require("../../assets/images/items/assets_imgs_items_bluebutterflychain.png"),
  platinumDiamondNecklace: require("../../assets/images/items/assets_imgs_items_platinumdiamondnecklace.png"),
  maroonRibbonScarf: require("../../assets/images/items/assets_imgs_items_maroonribbonscarf.png"),
  shitakeMushroom: require("../../assets/images/items/assets_imgs_items_shitakemushroom.png"),
  beeAntennae: require("../../assets/images/items/assets_imgs_items_beeantennae.png"),
  batHeadband: require("../../assets/images/items/assets_imgs_items_batheadband.png"),
  rubyHairBow: require("../../assets/images/items/assets_imgs_items_rubyhairbow.png"),
  deathCapMushroom: require("../../assets/images/items/assets_imgs_items_deathcapmushroom.png"),
  baseBallCap: require("../../assets/images/items/assets_imgs_items_baseballcap.png"),
  backwardsCap: require("../../assets/images/items/assets_imgs_items_backwardscap.png"),
  beigeBeret: require("../../assets/images/items/assets_imgs_items_beigeberet.png"),
  cherryBlossomCrown: require("../../assets/images/items/assets_imgs_items_cherryblossomcrown.png"),
  tropicalWreath: require("../../assets/images/items/assets_imgs_items_tropicalwreath.png"),

  // EPIC
  chunkyKnitScarf: require("../../assets/images/items/assets_imgs_items_chunkyknitscarf.png"),
  fallCamelScarf: require("../../assets/images/items/assets_imgs_items_fallcamelscarf.png"),
  warmPinkScarf: require("../../assets/images/items/assets_imgs_items_warmpinkscarf.png"),
  cowboyScarf: require("../../assets/images/items/assets_imgs_items_cowboyscarf.png"),
  aquaSpikedCollar: require("../../assets/images/items/assets_imgs_items_aquaspikedcollar.png"),
  hibiscusChain: require("../../assets/images/items/assets_imgs_items_hibiscuschain.png"),
  orangeButterflyChain: require("../../assets/images/items/assets_imgs_items_orangebutterflychain.png"),
  goldDiamondNecklace: require("../../assets/images/items/assets_imgs_items_golddiamondnecklace.png"),
  blackSpikedCollar: require("../../assets/images/items/assets_imgs_items_blackspikedcollar.png"),
  pinkSpikedCollar: require("../../assets/images/items/assets_imgs_items_pinkspikedcollar.png"),
  topHat: require("../../assets/images/items/assets_imgs_items_tophat.png"),
  cowboyHat: require("../../assets/images/items/assets_imgs_items_cowboyhat.png"),
  coralSunHat: require("../../assets/images/items/assets_imgs_items_coralsunhat.png"),
  yellowPalmCap: require("../../assets/images/items/assets_imgs_items_yellowpalmcap.png"),
  bluePalmCap: require("../../assets/images/items/assets_imgs_items_bluepalmcap.png"),
  hibiscusFlower: require("../../assets/images/items/assets_imgs_items_hibiscusflower.png"),
  peonyWreath: require("../../assets/images/items/assets_imgs_items_peonywreath.png"),
  spiderHat: require("../../assets/images/items/assets_imgs_items_spiderhat.png"),
  purpleBeanie: require("../../assets/images/items/assets_imgs_items_purplebeanie.png"),
  redHat: require("../../assets/images/items/assets_imgs_items_redhat.png"),

  // TRINKETS
  nailBuffers: require("../../assets/images/items/assets_imgs_items_nailbuffers.png"),
  leatherJournal: require("../../assets/images/items/assets_imgs_items_leatherjournal.png"),
  lycheeCandle: require("../../assets/images/items/assets_imgs_items_lycheecandle.png"),
  yogaMat: require("../../assets/images/items/assets_imgs_items_yogamat.png"),
  weightedBlanket: require("../../assets/images/items/assets_imgs_items_weightedblanket.png"),
  stressBall: require("../../assets/images/items/assets_imgs_items_stressball.png"),
  fuzzyMittens: require("../../assets/images/items/assets_imgs_items_fuzzymittens.png"),
  espressoShot: require("../../assets/images/items/assets_imgs_items_espressoshot.png"),
  fluffyPillow: require("../../assets/images/items/assets_imgs_items_fluffypillow.png"),
  softDumbbell: require("../../assets/images/items/assets_imgs_items_softdumbbell.png"),

  // LEGENDARY
  rubyCollar: require("../../assets/images/items/assets_imgs_items_rubycollar.png"),
  sorrowScarf: require("../../assets/images/items/assets_imgs_items_sorrowscarf.png"),
  anxietyScarf: require("../../assets/images/items/assets_imgs_items_anxietyscarf.png"),
  angryScarf: require("../../assets/images/items/assets_imgs_items_angryscarf.png"),
  enviousScarf: require("../../assets/images/items/assets_imgs_items_enviousscarf.png"),
  cakeScarf: require("../../assets/images/items/assets_imgs_items_cakescarf.png"),
  paisleyCowboyScarf: require("../../assets/images/items/assets_imgs_items_paisleycowboyscarf.png"),
  checkeredScarf: require("../../assets/images/items/assets_imgs_items_checkeredscarf.png"),
  bejeweledPinkScarf: require("../../assets/images/items/assets_imgs_items_bejeweledpinkscarf.png"),
  mermaidScarf: require("../../assets/images/items/assets_imgs_items_mermaidscarf.png"),
  watermelonSpikedCollar: require("../../assets/images/items/assets_imgs_items_watermelonspikedcollar.png"),
  lemonDolphinFloat: require("../../assets/images/items/assets_imgs_items_lemondolphinfloat.png"),
  serpentScarf: require("../../assets/images/items/assets_imgs_items_serpentscarf.png"),
  spiderNecklace: require("../../assets/images/items/assets_imgs_items_spidernecklace.png"),
  bubblegumScarf: require("../../assets/images/items/assets_imgs_items_bubblegumscarf.png"),
  jellyfishScarf: require("../../assets/images/items/assets_imgs_items_jellyfishscarf.png"),
  princesCollar: require("../../assets/images/items/assets_imgs_items_princescollar.png"),
  rubberRingDonut: require("../../assets/images/items/assets_imgs_items_rubberringdonut.png"),
  wizardCape: require("../../assets/images/items/assets_imgs_items_wizardcape.png"),
  blueTie: require("../../assets/images/items/assets_imgs_items_bluetie.png"),
  feltFedora: require("../../assets/images/items/assets_imgs_items_feltfedora.png"),
  titaniumTiara: require("../../assets/images/items/assets_imgs_items_titaniumtiara.png"),
  silkTopHat: require("../../assets/images/items/assets_imgs_items_silktophat.png"),
  cakeHat: require("../../assets/images/items/assets_imgs_items_cakehat.png"),
  floralCrochetHat: require("../../assets/images/items/assets_imgs_items_floralcrochethat.png"),
  wizardHat: require("../../assets/images/items/assets_imgs_items_wizardhat.png"),
  goldenHalo: require("../../assets/images/items/assets_imgs_items_goldenhalo.png"),
  redHorns: require("../../assets/images/items/assets_imgs_items_redhorns.png"),
  unicornHorns: require("../../assets/images/items/assets_imgs_items_unicornhorn.png"), // Adjust if your file name differs!
  rainbowPartyHat: require("../../assets/images/items/assets_imgs_items_rainbowpartyhat.png"),
  bejeweledCowboyHat: require("../../assets/images/items/assets_imgs_items_bejeweledcowboyhat.png"),
  pirateHat: require("../../assets/images/items/assets_imgs_items_piratehat.png"),
  iceCreamHat: require("../../assets/images/items/assets_imgs_items_icecreamhat.png"),
  pinwheelHat: require("../../assets/images/items/assets_imgs_items_pinwheelhat.png"),
  pearlClocheHat: require("../../assets/images/items/assets_imgs_items_pearlclochehat.png"),
  icyTiara: require("../../assets/images/items/assets_imgs_items_icytiara.png"),
  chefHat: require("../../assets/images/items/assets_imgs_items_chefhat.png"),
  specialTopHat: require("../../assets/images/items/assets_imgs_items_specialtophat.png"),
  karenHair: require("../../assets/images/items/assets_imgs_items_karenhair.png"),
  plungerHat: require("../../assets/images/items/assets_imgs_items_plungerhat.png"),

  // UBER
  parasiteScarf: require("../../assets/images/items/assets_imgs_items_parasitescarf.png"),
  dogeScarf: require("../../assets/images/items/assets_imgs_items_dogescarf.png"),
  alkalineEstrangementScarf: require("../../assets/images/items/assets_imgs_items_alkalineestrangementscarf.png"),
  adventureBuddyHat: require("../../assets/images/items/assets_imgs_items_adventurebuddyhat.png"),
  laserChickenHat: require("../../assets/images/items/assets_imgs_items_laserchickenhat.png"),
  lonelyHat: require("../../assets/images/items/assets_imgs_items_lonelyhat.png"),
};

export const getItemImage = (id: ItemId) => ITEMS_IMAGES[id];
