import { Item, ItemId } from "./item.type";

export const ITEMS_CONFIG: Record<ItemId, Item> = {
  // ------------- common -------------
  retroPinkFlowerCollar: {
    id: "retroPinkFlowerCollar",
    name: "Retro Pink Flower Collar",
    baseStats: { defense: 10 },
    rarity: "common",
    slot: "neck",
  },
  redBowTie: {
    id: "redBowTie",
    name: "Red Bow Tie",
    baseStats: { stamina: 10 },
    rarity: "common",
    slot: "neck",
  },
  peachDolphinFloat: {
    id: "peachDolphinFloat",
    name: "Peach Dolphin Float",
    baseStats: { speed: 3 },
    rarity: "common",
    slot: "neck",
  },
  turquoiseHeartCollar: {
    id: "turquoiseHeartCollar",
    name: "Turquoise Heart Collar",
    baseStats: { attack: 10 },
    rarity: "common",
    slot: "neck",
  },
  daisyChain: {
    id: "daisyChain",
    name: "Daisy Chain",
    baseStats: { crit: 2 },
    rarity: "common",
    slot: "neck",
  },
  leaf: {
    id: "leaf",
    name: "Leaf",
    baseStats: { speed: 3 },
    rarity: "common",
    slot: "hat",
  },
  cosmosFlower: {
    id: "cosmosFlower",
    name: "Cosmos Flower",
    baseStats: { defense: 10 },
    rarity: "common",
    slot: "hat",
  },
  pinkDandelion: {
    id: "pinkDandelion",
    name: "Pink Dandelion",
    baseStats: { attack: 10 },
    rarity: "common",
    slot: "hat",
  },
  dandelion: {
    id: "dandelion",
    name: "Dandelion",
    baseStats: { crit: 2 },
    rarity: "common",
    slot: "hat",
  },
  amanitaMushroom: {
    id: "amanitaMushroom",
    name: "Amanita Mushroom",
    baseStats: { stamina: 10 },
    rarity: "common",
    slot: "hat",
  },

  // ------------- rare -------------
  diamondCollar: {
    id: "diamondCollar",
    name: "Diamond Collar",
    baseStats: { crit: 1.4, attack: 7 },
    rarity: "rare",
    slot: "neck",
  },
  redRibbonScarf: {
    id: "redRibbonScarf",
    name: "Red Ribbon Scarf",
    baseStats: { stamina: 7, attack: 7 },
    rarity: "rare",
    slot: "neck",
  },
  blueRibbonScarf: {
    id: "blueRibbonScarf",
    name: "Blue Ribbon Scarf",
    baseStats: { defense: 7, crit: 1.4 },
    rarity: "rare",
    slot: "neck",
  },
  yellowRibbonScarf: {
    id: "yellowRibbonScarf",
    name: "Yellow Ribbon Scarf",
    baseStats: { stamina: 7, defense: 7 },
    rarity: "rare",
    slot: "neck",
  },
  greenRibbonScarf: {
    id: "greenRibbonScarf",
    name: "Green Ribbon Scarf",
    baseStats: { speed: 2, defense: 7 },
    rarity: "rare",
    slot: "neck",
  },
  lavenderRibbonScarf: {
    id: "lavenderRibbonScarf",
    name: "Lavender Ribbon Scarf",
    baseStats: { stamina: 7, speed: 2 },
    rarity: "rare",
    slot: "neck",
  },
  seaDolphinFloat: {
    id: "seaDolphinFloat",
    name: "Sea Dolphin Float",
    baseStats: { attack: 7, speed: 2 },
    rarity: "rare",
    slot: "neck",
  },
  blueButterflyChain: {
    id: "blueButterflyChain",
    name: "Blue Butterfly Chain",
    baseStats: { crit: 1.4, speed: 2 },
    rarity: "rare",
    slot: "neck",
  },
  platinumDiamondNecklace: {
    id: "platinumDiamondNecklace",
    name: "Platinum Diamond Necklace",
    baseStats: { crit: 1.4, stamina: 7 },
    rarity: "rare",
    slot: "neck",
  },
  maroonRibbonScarf: {
    id: "maroonRibbonScarf",
    name: "Maroon Ribbon Scarf",
    baseStats: { attack: 7, defense: 7 },
    rarity: "rare",
    slot: "neck",
  },
  shitakeMushroom: {
    id: "shitakeMushroom",
    name: "Shitake Mushroom",
    baseStats: { stamina: 7, defense: 7 },
    rarity: "rare",
    slot: "hat",
  },
  beeAntennae: {
    id: "beeAntennae",
    name: "Bee Antennae",
    baseStats: { attack: 7, speed: 2 },
    rarity: "rare",
    slot: "hat",
  },
  batHeadband: {
    id: "batHeadband",
    name: "Bat Headband",
    baseStats: { crit: 1.4, speed: 2 },
    rarity: "rare",
    slot: "hat",
  },
  rubyHairBow: {
    id: "rubyHairBow",
    name: "Ruby Hair Bow",
    baseStats: { stamina: 7, attack: 7 },
    rarity: "rare",
    slot: "hat",
  },
  deathCapMushroom: {
    id: "deathCapMushroom",
    name: "Death Cap Mushroom",
    baseStats: { speed: 2, defense: 7 },
    rarity: "rare",
    slot: "hat",
  },
  baseBallCap: {
    id: "baseBallCap",
    name: "Base Ball Cap",
    baseStats: { crit: 1.4, stamina: 7 },
    rarity: "rare",
    slot: "hat",
  },
  backwardsCap: {
    id: "backwardsCap",
    name: "Backwards Cap",
    baseStats: { crit: 1.4, attack: 7 },
    rarity: "rare",
    slot: "hat",
  },
  beigeBeret: {
    id: "beigeBeret",
    name: "Beige Beret",
    baseStats: { defense: 7, crit: 1.4 },
    rarity: "rare",
    slot: "hat",
  },
  cherryBlossomCrown: {
    id: "cherryBlossomCrown",
    name: "Cherry Blossom Crown",
    baseStats: { attack: 7, defense: 7 },
    rarity: "rare",
    slot: "hat",
  },
  tropicalWreath: {
    id: "tropicalWreath",
    name: "Tropical Wreath",
    baseStats: { speed: 2, stamina: 7 },
    rarity: "rare",
    slot: "hat",
  },

  // ------------- epic -------------
  cowboyHat: {
    id: "cowboyHat",
    name: "Cowboy Hat",
    baseStats: { stamina: 10, defense: 10 },
    rarity: "epic",
    slot: "hat",
  },
  coralSunHat: {
    id: "coralSunHat",
    name: "Coral Sun Hat",
    baseStats: { stamina: 10, speed: 3 },
    rarity: "epic",
    slot: "hat",
  },
  purpleBeanie: {
    id: "purpleBeanie",
    name: "Purple Beanie",
    baseStats: { crit: 2, defense: 10 },
    rarity: "epic",
    slot: "hat",
  },
  bluePalmCap: {
    id: "bluePalmCap",
    name: "Blue Palm Cap",
    baseStats: { defense: 10, speed: 3 },
    rarity: "epic",
    slot: "hat",
  },
  topHat: {
    id: "topHat",
    name: "Top Hat",
    baseStats: { stamina: 10, attack: 10 },
    rarity: "epic",
    slot: "hat",
  },
  yellowPalmCap: {
    id: "yellowPalmCap",
    name: "Yellow Palm Cap",
    baseStats: { speed: 3, crit: 2 },
    rarity: "epic",
    slot: "hat",
  },
  peonyWreath: {
    id: "peonyWreath",
    name: "Peony Wreath",
    baseStats: { attack: 10, defense: 10 },
    rarity: "epic",
    slot: "hat",
  },
  redHat: {
    id: "redHat",
    name: "Red Hat",
    baseStats: { crit: 2, stamina: 10 },
    rarity: "epic",
    slot: "hat",
  },
  hibiscusFlower: {
    id: "hibiscusFlower",
    name: "Hibiscus Flower",
    baseStats: { attack: 10, speed: 3 },
    rarity: "epic",
    slot: "hat",
  },
  spiderHat: {
    id: "spiderHat",
    name: "Spider Hat",
    baseStats: { crit: 2, attack: 10 },
    rarity: "epic",
    slot: "hat",
  },
  cowboyScarf: {
    id: "cowboyScarf",
    name: "Cowboy Scarf",
    baseStats: { stamina: 10, defense: 10 },
    rarity: "epic",
    slot: "neck",
  },
  warmPinkScarf: {
    id: "warmPinkScarf",
    name: "Warm Pink Scarf",
    baseStats: { stamina: 10, speed: 3 },
    rarity: "epic",
    slot: "neck",
  },
  chunkyKnitScarf: {
    id: "chunkyKnitScarf",
    name: "Chunky Knit Scarf",
    baseStats: { stamina: 10, attack: 10 },
    rarity: "epic",
    slot: "neck",
  },
  fallCamelScarf: {
    id: "fallCamelScarf",
    name: "Fall Camel Scarf",
    baseStats: { defense: 10, speed: 3 },
    rarity: "epic",
    slot: "neck",
  },
  aquaSpikedCollar: {
    id: "aquaSpikedCollar",
    name: "Aqua Spiked Collar",
    baseStats: { crit: 2, speed: 3 },
    rarity: "epic",
    slot: "neck",
  },
  hibiscusChain: {
    id: "hibiscusChain",
    name: "Hibiscus Chain",
    baseStats: { speed: 3, attack: 10 },
    rarity: "epic",
    slot: "neck",
  },
  orangeButterflyChain: {
    id: "orangeButterflyChain",
    name: "Orange Butterfly Chain",
    baseStats: { defense: 10, attack: 10 },
    rarity: "epic",
    slot: "neck",
  },
  goldDiamondNecklace: {
    id: "goldDiamondNecklace",
    name: "Gold Diamond Necklace",
    baseStats: { crit: 2, defense: 10 },
    rarity: "epic",
    slot: "neck",
  },
  blackSpikedCollar: {
    id: "blackSpikedCollar",
    name: "Black Spiked Collar",
    baseStats: { crit: 2, attack: 10 },
    rarity: "epic",
    slot: "neck",
  },
  pinkSpikedCollar: {
    id: "pinkSpikedCollar",
    name: "Pink Spiked Collar",
    baseStats: { crit: 2, stamina: 10 },
    rarity: "epic",
    slot: "neck",
  },

  // ------------- trinkets -------------
  nailBuffers: {
    id: "nailBuffers",
    name: "Nail Buffers",
    baseStats: { attack: 7 },
    rarity: "rare",
    slot: "trinket",
  },
  leatherJournal: {
    id: "leatherJournal",
    name: "Leather Journal",
    baseStats: { crit: 1.4 },
    rarity: "rare",
    slot: "trinket",
  },
  lycheeCandle: {
    id: "lycheeCandle",
    name: "Lychee Candle",
    baseStats: { speed: 2 },
    rarity: "rare",
    slot: "trinket",
  },
  yogaMat: {
    id: "yogaMat",
    name: "Yoga Mat",
    baseStats: { stamina: 7 },
    rarity: "rare",
    slot: "trinket",
  },
  weightedBlanket: {
    id: "weightedBlanket",
    name: "Weighted Blanket",
    baseStats: { defense: 7 },
    rarity: "rare",
    slot: "trinket",
  },

  stressBall: {
    id: "stressBall",
    name: "Stress Ball",
    baseStats: { crit: 2 },
    rarity: "epic",
    slot: "trinket",
  },
  fuzzyMittens: {
    id: "fuzzyMittens",
    name: "Fuzzy Mittens",
    baseStats: { defense: 10 },
    rarity: "epic",
    slot: "trinket",
  },
  espressoShot: {
    id: "espressoShot",
    name: "Espresso Shot",
    baseStats: { speed: 3 },
    rarity: "epic",
    slot: "trinket",
  },
  fluffyPillow: {
    id: "fluffyPillow",
    name: "Fluffy Pillow",
    baseStats: { stamina: 10 },
    rarity: "epic",
    slot: "trinket",
  },
  softDumbbell: {
    id: "softDumbbell",
    name: "Soft Dumbbell",
    baseStats: { attack: 10 },
    rarity: "epic",
    slot: "trinket",
  },

  // ------------- legendary -------------
  rubyCollar: {
    id: "rubyCollar",
    name: "Ruby Collar",
    baseStats: { attack: 15, crit: 3.2 },
    rarity: "legendary",
    slot: "neck",
  },
  sorrowScarf: {
    id: "sorrowScarf",
    name: "Sorrow Scarf",
    baseStats: { defense: 15, speed: 4 },
    rarity: "legendary",
    slot: "neck",
  },
  anxietyScarf: {
    id: "anxietyScarf",
    name: "Anxiety Scarf",
    baseStats: { attack: 15, crit: 4 },
    rarity: "legendary",
    slot: "neck",
  },
  angryScarf: {
    id: "angryScarf",
    name: "Angry Scarf",
    baseStats: { attack: 19, crit: 2.2 },
    rarity: "legendary",
    slot: "neck",
  },
  enviousScarf: {
    id: "enviousScarf",
    name: "Envious Scarf",
    baseStats: { defense: 15, crit: 3.2 },
    rarity: "legendary",
    slot: "neck",
  },
  cakeScarf: {
    id: "cakeScarf",
    name: "Cake Scarf",
    baseStats: { attack: 15, defense: 15 },
    rarity: "legendary",
    slot: "neck",
  },
  paisleyCowboyScarf: {
    id: "paisleyCowboyScarf",
    name: "Paisley Cowboy Scarf",
    baseStats: { stamina: 15, defense: 15 },
    rarity: "legendary",
    slot: "neck",
  },
  checkeredScarf: {
    id: "checkeredScarf",
    name: "Checkered Scarf",
    baseStats: { stamina: 15, defense: 15 },
    rarity: "legendary",
    slot: "neck",
  },
  bejeweledPinkScarf: {
    id: "bejeweledPinkScarf",
    name: "Bejeweled Pink Scarf",
    baseStats: { attack: 18, defense: 12 },
    rarity: "legendary",
    slot: "neck",
  },
  mermaidScarf: {
    id: "mermaidScarf",
    name: "Mermaid Scarf",
    baseStats: { stamina: 15, attack: 15 },
    rarity: "legendary",
    slot: "neck",
  },
  watermelonSpikedCollar: {
    id: "watermelonSpikedCollar",
    name: "Watermelon Spiked Collar",
    baseStats: { speed: 3, crit: 4.1 },
    rarity: "legendary",
    slot: "neck",
  },
  lemonDolphinFloat: {
    id: "lemonDolphinFloat",
    name: "Lemon Dolphin Float",
    baseStats: { stamina: 10, crit: 5 },
    rarity: "legendary",
    slot: "neck",
  },
  serpentScarf: {
    id: "serpentScarf",
    name: "Serpent Scarf",
    baseStats: { attack: 15, crit: 3.2 },
    rarity: "legendary",
    slot: "neck",
  },
  spiderNecklace: {
    id: "spiderNecklace",
    name: "Spider Necklace",
    baseStats: { attack: 15, crit: 3.2 },
    rarity: "legendary",
    slot: "neck",
  },
  bubblegumScarf: {
    id: "bubblegumScarf",
    name: "Bubblegum Scarf",
    baseStats: { stamina: 12, crit: 5 },
    rarity: "legendary",
    slot: "neck",
  },
  jellyfishScarf: {
    id: "jellyfishScarf",
    name: "Jellyfish Scarf",
    baseStats: { stamina: 7, attack: 22 },
    rarity: "legendary",
    slot: "neck",
  },
  princesCollar: {
    id: "princesCollar",
    name: "Prince's Collar",
    baseStats: { stamina: 12, defense: 18 },
    rarity: "legendary",
    slot: "neck",
  },
  rubberRingDonut: {
    id: "rubberRingDonut",
    name: "Rubber Ring Donut",
    baseStats: { attack: 18, speed: 3 },
    rarity: "legendary",
    slot: "neck",
  },
  wizardCape: {
    id: "wizardCape",
    name: "Wizard Cape",
    baseStats: { attack: 15, speed: 4 },
    rarity: "legendary",
    slot: "neck",
  },
  blueTie: {
    id: "blueTie",
    name: "Blue Tie",
    baseStats: { speed: 4, crit: 3.2 },
    rarity: "legendary",
    slot: "neck",
  },

  feltFedora: {
    id: "feltFedora",
    name: "Felt Fedora",
    baseStats: { attack: 15, defense: 15 },
    rarity: "legendary",
    slot: "hat",
  },
  titaniumTiara: {
    id: "titaniumTiara",
    name: "Titanium Tiara",
    baseStats: { defense: 18, crit: 2.5 },
    rarity: "legendary",
    slot: "hat",
  },
  silkTopHat: {
    id: "silkTopHat",
    name: "Silk Top Hat",
    baseStats: { attack: 19, crit: 2.2 },
    rarity: "legendary",
    slot: "hat",
  },
  cakeHat: {
    id: "cakeHat",
    name: "Cake Hat",
    baseStats: { defense: 15, crit: 4 },
    rarity: "legendary",
    slot: "hat",
  },
  floralCrochetHat: {
    id: "floralCrochetHat",
    name: "Floral Crochet Hat",
    baseStats: { stamina: 15, defense: 15 },
    rarity: "legendary",
    slot: "hat",
  },
  wizardHat: {
    id: "wizardHat",
    name: "Wizard Hat",
    baseStats: { attack: 18, defense: 12 },
    rarity: "legendary",
    slot: "hat",
  },
  goldenHalo: {
    id: "goldenHalo",
    name: "Golden Halo",
    baseStats: { stamina: 15, attack: 15 },
    rarity: "legendary",
    slot: "hat",
  },
  redHorns: {
    id: "redHorns",
    name: "Red Horns",
    baseStats: { attack: 10, crit: 4.1 },
    rarity: "legendary",
    slot: "hat",
  },
  unicornHorns: {
    id: "unicornHorns",
    name: "Unicorn Horn",
    baseStats: { attack: 18, crit: 3 },
    rarity: "legendary",
    slot: "hat",
  },
  rainbowPartyHat: {
    id: "rainbowPartyHat",
    name: "Rainbow Party Hat",
    baseStats: { speed: 5, crit: 2.5 },
    rarity: "legendary",
    slot: "hat",
  },
  bejeweledCowboyHat: {
    id: "bejeweledCowboyHat",
    name: "Bejeweled Cowboy Hat",
    baseStats: { stamina: 22, defense: 7 },
    rarity: "legendary",
    slot: "hat",
  },
  pirateHat: {
    id: "pirateHat",
    name: "Pirate Hat",
    baseStats: { stamina: 15, attack: 15 },
    rarity: "legendary",
    slot: "hat",
  },
  iceCreamHat: {
    id: "iceCreamHat",
    name: "Ice Cream Hat",
    baseStats: { attack: 15, crit: 4 },
    rarity: "legendary",
    slot: "hat",
  },
  pinwheelHat: {
    id: "pinwheelHat",
    name: "Pinwheel Hat",
    baseStats: { stamina: 18, crit: 2.5 },
    rarity: "legendary",
    slot: "hat",
  },
  pearlClocheHat: {
    id: "pearlClocheHat",
    name: "Pearl Cloche Hat",
    baseStats: { stamina: 12, crit: 5 },
    rarity: "legendary",
    slot: "hat",
  },
  icyTiara: {
    id: "icyTiara",
    name: "Icy Tiara",
    baseStats: { defense: 15, crit: 4 },
    rarity: "legendary",
    slot: "hat",
  },
  chefHat: {
    id: "chefHat",
    name: "Chef Hat",
    baseStats: { stamina: 18, crit: 3 },
    rarity: "legendary",
    slot: "hat",
  },
  specialTopHat: {
    id: "specialTopHat",
    name: "Special Top Hat",
    baseStats: { attack: 15, crit: 3.2 },
    rarity: "legendary",
    slot: "hat",
  },
  karenHair: {
    id: "karenHair",
    name: "Karen Hair",
    baseStats: { stamina: 12, defense: 18 },
    rarity: "legendary",
    slot: "hat",
  },
  plungerHat: {
    id: "plungerHat",
    name: "Plunger Hat",
    baseStats: { stamina: 15, attack: 15, defense: 15, speed: 4, crit: 3.2 },
    rarity: "legendary",
    slot: "hat",
  },

  // ------------- uber -------------
  parasiteScarf: {
    id: "parasiteScarf",
    name: "Parasite Scarf",
    baseStats: { attack: 20, crit: 4.7 },
    rarity: "uber",
    slot: "neck",
  },
  dogeScarf: {
    id: "dogeScarf",
    name: "Doge Scarf",
    baseStats: { defense: 20, speed: 5 },
    rarity: "uber",
    slot: "neck",
  },
  alkalineEstrangementScarf: {
    id: "alkalineEstrangementScarf",
    name: "Alkaline Estrangement Scarf",
    baseStats: { stamina: 20, speed: 5 },
    rarity: "uber",
    slot: "neck",
  },

  adventureBuddyHat: {
    id: "adventureBuddyHat",
    name: "Adventure Buddy Hat",
    baseStats: { attack: 20, speed: 5 },
    rarity: "uber",
    slot: "hat",
  },
  laserChickenHat: {
    id: "laserChickenHat",
    name: "Laser Chicken Hat",
    baseStats: { attack: 40 },
    rarity: "uber",
    slot: "hat",
  },
  lonelyHat: {
    id: "lonelyHat",
    name: "Lonely Hat",
    baseStats: { stamina: 20, speed: 5 },
    rarity: "uber",
    slot: "hat",
  },
};
export const getItem = (id: ItemId) => ITEMS_CONFIG[id];
