export type ItemStats = {
  attack?: number;
  defense?: number;
  speed?: number;
  stamina?: number;
  crit?: number;
};

export type ItemRarity = "common" | "rare" | "epic" | "legendary" | "uber";

export type Item = {
  id: ItemId;
  name: string;
  description?: string;
  baseStats: ItemStats;
  rarity: ItemRarity;
  slot: "hat" | "neck" | "trinket";
  image: string;
};

export type ItemId =
  // common
  | "retroPinkFlowerCollar"
  | "redBowTie"
  | "peachDolphinFloat"
  | "turquoiseHeartCollar"
  | "daisyChain"
  | "leaf"
  | "cosmosFlower"
  | "pinkDandelion"
  | "dandelion"
  | "amanitaMushroom"
  // rare
  | "diamondCollar"
  | "redRibbonScarf"
  | "blueRibbonScarf"
  | "yellowRibbonScarf"
  | "greenRibbonScarf"
  | "lavenderRibbonScarf"
  | "seaDolphinFloat"
  | "blueButterflyChain"
  | "platinumDiamondNecklace"
  | "maroonRibbonScarf"
  | "shitakeMushroom"
  | "beeAntennae"
  | "batHeadband"
  | "rubyHairBow"
  | "deathCapMushroom"
  | "baseBallCap"
  | "backwardsCap"
  | "beigeBeret"
  | "cherryBlossomCrown"
  | "tropicalWreath"
  // epic
  | "chunkyKnitScarf"
  | "fallCamelScarf"
  | "warmPinkScarf"
  | "cowboyScarf"
  | "aquaSpikedCollar"
  | "hibiscusChain"
  | "orangeButterflyChain"
  | "goldDiamondNecklace"
  | "blackSpikedCollar"
  | "pinkSpikedCollar"
  | "topHat"
  | "cowboyHat"
  | "coralSunHat"
  | "yellowPalmCap"
  | "bluePalmCap"
  | "hibiscusFlower"
  | "peonyWreath"
  | "spiderHat"
  | "purpleBeanie"
  | "redHat"
  // trinkets
  | "nailBuffers"
  | "leatherJournal"
  | "lycheeCandle"
  | "yogaMat"
  | "weightedBlanket"
  | "stressBall"
  | "fuzzyMittens"
  | "espressoShot"
  | "fluffyPillow"
  | "softDumbbell"
  // legendary
  | "rubyCollar"
  | "sorrowScarf"
  | "anxietyScarf"
  | "angryScarf"
  | "enviousScarf"
  | "cakeScarf"
  | "paisleyCowboyScarf"
  | "checkeredScarf"
  | "bejeweledPinkScarf"
  | "mermaidScarf"
  | "watermelonSpikedCollar"
  | "lemonDolphinFloat"
  | "serpentScarf"
  | "spiderNecklace"
  | "bubblegumScarf"
  | "jellyfishScarf"
  | "princesCollar"
  | "rubberRingDonut"
  | "wizardCape"
  | "blueTie"
  | "feltFedora"
  | "titaniumTiara"
  | "silkTopHat"
  | "cakeHat"
  | "floralCrochetHat"
  | "wizardHat"
  | "goldenHalo"
  | "redHorns"
  | "unicornHorns"
  | "rainbowPartyHat"
  | "bejeweledCowboyHat"
  | "pirateHat"
  | "iceCreamHat"
  | "pinwheelHat"
  | "pearlClocheHat"
  | "icyTiara"
  | "chefHat"
  | "specialTopHat"
  | "karenHair"
  | "plungerHat"
  // uber
  | "parasiteScarf"
  | "dogeScarf"
  | "alkalineEstrangementScarf"
  | "adventureBuddyHat"
  | "laserChickenHat"
  | "lonelyHat";
